# # version of node we want.
# FROM node:13.8.0-alpine
# RUN mkdir -p /app/client
# WORKDIR /app/client
# COPY yarn.lock /app/client
# COPY package.json /app/client
# RUN yarn install
# COPY . /app/client
# CMD ["yarn", "start"]

